### ISSUE TITLE
Different image for targets?

### ISSUE THREAD

**Issue by albertrdixon** [lumoslabs/broadside#10]
Is it possible to supply a different image for different targets? 

My use case is this: 

I have a staging image - `quay.io/me/widget-staging` - and a trimmed production image - `quay.io/me/widget-production` - and I would like to do something like this if I want to deploy staging: `broadside deploy short --target staging_web --image quay.io/me/widget-staging --tag feature-branch`

**Comment by apurvis** [comment]
https://github.com/lumoslabs/broadside/pull/49/commits/a886962cf358f1a5ea84efe1b03b62ba1bfd3e44
