### ISSUE TITLE
Unknown option --config

### ISSUE THREAD

**Issue by jagaapple** [lumoslabs/broadside#104]
Can we specify a config file path via CLI? By [the wiki](https://github.com/lumoslabs/broadside/wiki/Configuration#configuring-broadside), it is possible to do using `--config` option, but it does not work with `error: Unknown option --config` .

```sh
$ bundle exec broadside bootstrap --target app --config config/deploy/development.yml 
error: Unknown option --config
```

> By default, the CLI will assume the existence of a config/broadside.conf.rb file in your application root directory. You can also manually specify a config file for an individual execution with --config config/to/my/other/broadside.conf.rb.
>
> https://github.com/lumoslabs/broadside/wiki/Configuration#configuring-broadside

Or this option is removed?

*broadside ver 3.3.2*

**Comment by jagaapple** [comment]
I've found out it is a kind of the global options, so we must use the option between `broadside` and `bootstrap` like `bundle exec broadside --config XXX bootstrap ...` .
Sorry my poor issue 😥

**Comment by camertron** [comment]
Glad you figured it out, @jagaapple :)

**Comment by apurvis** [comment]
FWIW this is because of how [GLI](https://github.com/davetron5000/gli) (which broadside is built on) processes command line arguments
