### ISSUE TITLE
deploy should update task_definition and service with latest configuration options IF they are configured

### ISSUE THREAD

**Issue by apurvis** [lumoslabs/broadside#31]
When deploying, the new task definition revision should be overridden with anything configured at `:task_definition_config`, and the service should be updated with anything configured at `:service_config`

DE-11348

cc @matl33t

**Comment by apurvis** [comment]
one gotcha is that rolling back will not be able to rollback the service changes.

**Comment by matl33t** [comment]
yeah that's right, but at least the config will be presumably under version control

**Comment by apurvis** [comment]
added in #32
