### ISSUE TITLE
let an app deploy to multiple clusters

### ISSUE THREAD

**Issue by matl33t** [lumoslabs/broadside#5]
Currently only supports one cluster per application, but some applications may want to have separate staging/production clusters.

**Comment by apurvis** [comment]
relevant discussion about ditching `EcsConfig` class: https://github.com/lumoslabs/broadside/pull/16#pullrequestreview-1847317

**Comment by apurvis** [comment]
resolved by https://github.com/lumoslabs/broadside/pull/44
