### ISSUE TITLE
killed by signal 1

### ISSUE THREAD

**Issue by rfroetscher** [lumoslabs/broadside#7]
@matl33t 

I, [2016-07-19_14:24:12#22530]  INFO -- : airflow upgradedb task container logs:
STDOUT:--
[2016-07-19 21:24:09,077] {__init__.py:36} INFO - Using executor CeleryExecutor
[2016-07-19 21:24:09,148] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2016-07-19 21:24:09,168] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
DB: mysql://airflow:***@airflow-analytics.cluster-cdiwpivlvfxt.us-east-1.rds.amazonaws.com/airflow
[2016-07-19 21:24:09,380] {db.py:222} INFO - Creating tables

STDERR:--
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Killed by signal 1.

D, [2016-07-19_14:24:12#22530] DEBUG -- : Deregistered arn:aws:ecs:us-east-1:447374670232:task-definition/airflow_web:188
error: airflow upgradedb task arn:aws:ecs:us-east-1:447374670232:task/5ad56f33-2cc8-4093-b7bd-0a66c4c5df73 exited with a non-zero status code !

is this an ssh problem?
http://stackoverflow.com/questions/12639615/cygwin-ssh-gives-killed-by-signal-1-on-exit

**Comment by matl33t** [comment]
is this a full deployment or a one-off task being run?

**Comment by rfroetscher** [comment]
full deployment with a predeploy command

setup is on catapult-aws in ~/lumos_airflow/deploy.sh

**Comment by matl33t** [comment]
I believe the problem here was that https://github.com/lumoslabs/broadside/pull/8/files#diff-23ab6a0d1e964333ab189e77672276d6L254 incorrectly assumes the first listed container of the task will be the application container. In this case, it was an nginx container that exited without a proper status code, and the correct status code from the application container was ignored.

**Comment by rfroetscher** [comment]
makes sense. thanks
