### ISSUE TITLE
Pass more to Pre/Post hooks

### ISSUE THREAD

**Issue by albertrdixon** [lumoslabs/broadside#9]
Would love to get more information in the pre and post hook blocks, in particular the command line flags and their values.

**Comment by apurvis** [comment]
so this is about passing the command line options into the pre and posthoook blocks?

**Comment by apurvis** [comment]
@matl33t is this still relevant?

**Comment by matl33t** [comment]
This is now complete. @albertrdixon in case you're still interested, https://github.com/lumoslabs/broadside/wiki/Configuration#hooks now lists some additional keys that contains some of that useful info
